/*------------------------------------------------------------
Author: Aman Mundhada
Company: Persistent Systems
Description: This class is wrapper class Error response for the IBB API
Test Class:
History
Date            Author              Comments
------------------------------------------------------------- 
05-04-2021    Aman Mundhada            Created
------------------------------------------------------------*/
public class IBBErrorResponse extends ParentAPIResponse {
   public String status;
   public String message;
}