@isTest
public class IND_LWC_StpChecksCntrlTest1 {  
    
  /*  public static Opportunity testOpportunityNewData(){
        Opportunity opsc1 = new Opportunity();
            opsc1.StageName = 'Qualification';
            opsc1.CloseDate = Date.newInstance(2022, 1, 11);
            opsc1.Name = 'testone';
            opsc1.Vehicle_Type__c = 'New';
            opsc1.Product_Type__c = 'Two Wheeler';
        insert opsc1;
        return opsc1;
    }
    
    public static Opportunity testOpportunityUsedData(){
        Opportunity opsc1 = new Opportunity();
            opsc1.StageName = 'Qualification';
            opsc1.CloseDate = Date.newInstance(2022, 1, 11);
            opsc1.Name = 'testone';
            opsc1.Vehicle_Type__c = 'Used';
            opsc1.Product_Type__c = 'Two Wheeler';
        insert opsc1;
        return opsc1;
    }
    
    public static Applicant__c testApplicantData(){
        Opportunity opsc2 = testOpportunityNewData();
        Applicant__c apsc2 = new Applicant__c();
            apsc2.Opportunity__c = opsc2.Id;
            apsc2.Contact_number__c = '9743514830';
            apsc2.Applicant_Type__c = 'Borrower';
        insert apsc2;
        return apsc2;
    }
    
    public static Customer_Code__c testCustomerCodeData(){
        Opportunity opsc2 = testOpportunityNewData();
        Customer_Code__c cust = new Customer_Code__c();
            cust.Name='newcust';
            cust.Loan_Application__c = opsc2.Id;
            insert cust;
        return cust;
    }
   Test3---
            Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
            opsc2.Product_Type__c = 'Passenger Vehicles';
            opsc2.Loan_amount__c = '6000000';
             opsc2.Vehicle_Details_Retry_Attempt__c=1;
            opsc2.Vehicle_Type__c = 'used';
            insert opsc2;

	Test4--- 
            Opportunity opsc1 = new Opportunity();
            opsc1.StageName = 'Qualification';
            opsc1.CloseDate = Date.newInstance(2022, 1, 11);
            opsc1.Name = 'testone';
            opsc1.Vehicle_Type__c = 'New';
            opsc1.Product_Type__c = 'Two Wheeler';
            insert opsc1;
	Test6---
		 
     Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
          //  opsc1.Vehicle_Type__c = 'New';
            opsc2.Product_Type__c = 'Passenger Vehicles';
            opsc2.Loan_amount__c = '6000000';
             opsc2.Vehicle_Details_Retry_Attempt__c=1;
            opsc2.Vehicle_Type__c = 'used';
            insert opsc2;
       
            
*/  
    /* test7-- 
         Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
            opsc2.Vehicle_Type__c = 'New';
            opsc2.Product_Type__c = 'Passenger Vehicles';
            opsc2.Loan_amount__c = '6000000';
            opsc2.Vehicle_Details_Retry_Attempt__c = 1;
        	opsc2.Total_Funded_premium_amount__c = 40000 ; 
  
            insert opsc2;
        */
    /*Test 6 ---
     Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
          //  opsc1.Vehicle_Type__c = 'New';
            opsc2.Product_Type__c = 'Passenger Vehicles';
            opsc2.Loan_amount__c = '6000000';
             opsc2.Vehicle_Details_Retry_Attempt__c=1;
            opsc2.Vehicle_Type__c = 'used';
            insert opsc2;
       */
      /* Test5---
        Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
            opsc2.Product_Type__c = 'Passenger Vehicles';
            opsc2.Loan_amount__c = '6000000';
            opsc2.Vehicle_Details_Retry_Attempt__c=1;
            opsc2.Vehicle_Type__c = 'used';
            insert opsc2;
*/	
       /*Test2---
            Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
            opsc2.Vehicle_Type__c = 'Used';
            opsc2.Product_Type__c = 'Two Wheeler';
            opsc2.Loan_amount__c = '6000000';
            opsc2.Vehicle_Sub_Category__c = 'UEB';
            insert opsc2;
            */
     		
}